# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Invo < Formula
  desc "invo: a minimalist CLI tool for generating professional PDF invoices"
  homepage "https://github.com/yarlson/invo"
  version "0.1.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/yarlson/invo/releases/download/0.1.0/invo_0.1.0_darwin_amd64.tar.gz"
      sha256 "7a1a5e3dc81d4f60cf8c5042524b300c3b3ee8248c71d891e676bd2972b819ca"

      def install
        bin.install "invo"
      end
    end
    on_arm do
      url "https://github.com/yarlson/invo/releases/download/0.1.0/invo_0.1.0_darwin_arm64.tar.gz"
      sha256 "b84bb93ebde9505d17be3d1b08b73096091a4bcb0a9f6da9d608e847ebd974ba"

      def install
        bin.install "invo"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/yarlson/invo/releases/download/0.1.0/invo_0.1.0_linux_amd64.tar.gz"
        sha256 "82a7a92be57fbc82f08a9bfa28e504ce1f7c5e532c85767db02d4224cf84e97f"

        def install
          bin.install "invo"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/yarlson/invo/releases/download/0.1.0/invo_0.1.0_linux_arm64.tar.gz"
        sha256 "39024ea35d647ce66f33db8815f7c0cf65dddeb6cbe1e447280e551f8223c66e"

        def install
          bin.install "invo"
        end
      end
    end
  end

  test do
    system "#{bin}/invo --version"
  end
end
