# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Invo < Formula
  desc "invo: a minimalist CLI tool for generating professional PDF invoices"
  homepage "https://github.com/yarlson/invo"
  version "0.2.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/yarlson/invo/releases/download/0.2.0/invo_0.2.0_darwin_amd64.tar.gz"
      sha256 "a0fd8255b3792aeaf14b1c0cf2b5d77542ff5c7f2c66696296f64c5134fa16e3"

      def install
        bin.install "invo"
      end
    end
    on_arm do
      url "https://github.com/yarlson/invo/releases/download/0.2.0/invo_0.2.0_darwin_arm64.tar.gz"
      sha256 "5c55684ec1059f62b6f8736346e652133fada3b5422c7fac1a781c4a8e78c143"

      def install
        bin.install "invo"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/yarlson/invo/releases/download/0.2.0/invo_0.2.0_linux_amd64.tar.gz"
        sha256 "7f6a7b3835480074856353d0f281298b614a04fe93d868e41a7a3ee3b3197758"

        def install
          bin.install "invo"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/yarlson/invo/releases/download/0.2.0/invo_0.2.0_linux_arm64.tar.gz"
        sha256 "3a8b45b27914afeff79b520be0b2391158517b37e4748586defa38ecc6e1016c"

        def install
          bin.install "invo"
        end
      end
    end
  end

  test do
    system "#{bin}/invo --version"
  end
end
